//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by psruti_res_eng.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_PSRUTI_DIALOG               102
#define IDS_SelectSourceFirst           102
#define IDS_UseExistingFile             103
#define IDS_SelectDestinationFirst      104
#define IDS_SelectTransposeNumberFirst  106
#define IDS_ExitPSRUTIAndStartAgain     107
#define IDS_ChordFromChannel            108
#define IDS_ChordsFromChannel           109
#define IDS_KeySignature                110
#define IDS_WITH_XF_CHORDS              112
#define IDS_no_chords_on_chan           114
#define IDS_no_chords_in_song           115
#define IDS_overwrite_source            116
#define IDS_SaveChanges                 117
#define IDS_FILL_LYRICS                 118
#define IDS_FILL_LYRICS_INSERTED        119
#define IDS_XG_CONVERTED                120
#define IDS_ERROR_IN_LINE               121
#define IDS_MIDI_PORT                   122
#define IDS_PLAY                        123
#define IDS_ERROR_SOURCE                124
#define IDS_STRING125                   125
#define IDS_HP_INIT                     126
#define IDS_OVERFLOW_OFF_LIST           127
#define IDR_MAINFRAME                   128
#define IDS_ERROR_DEST                  128
#define IDD_SELECT_MIDI_DEVICE          129
#define IDS_CHORDLYRICFILE              129
#define IDC_DEVICE_LIST                 130
#define IDS_CHORDFILE_EMPTY             130
#define IDS_NO_XF_CHORDS_IN_FILE        131
#define IDS_USE_DRUM_KIT                132
#define IDS_NO_EXPR_MVOLUME_CHANGES     133
#define IDS_ADD_LYRICS_TO_OTHERS        134
#define IDS_SELECTSOURCE                135
#define IDS_SAVE                        136
#define IDS_TRANSPOSE                   137
#define IDS_COMPUTE_CHORDS              138
#define IDS_INSERT_FILL_LYRICS          139
#define IDD_TRANSPOSE_NO                140
#define IDS_SELECT_FILL_LYRICS_LINEFEED 140
#define IDS_TEMPO                       141
#define IDD_SLCTCHORDCHAN               142
#define IDS_VOLUME                      142
#define IDS_EXPR_MVOLUME                143
#define IDS_XG_CONVERT                  144
#define IDS_CHORDS_IMPORT_EXPORT        145
#define IDS_LYRIC_IMPORT_EXPORT         146
#define IDS_INFO                        147
#define IDS_HELP                        148
#define IDS_LANGUAGE                    149
#define IDS_SELECT_MIDI_DEVICE          150
#define IDS_START_PLAY                  151
#define IDS_PAUSE                       152
#define IDS_STOP                        153
#define IDS_EXIT                        154
#define IDS_STOP_PLAY                   155
#define IDS_SONGNAME                    156
#define IDS_VEL_COMPRESS                157
#define IDS_START_BEAT                  158
#define IDB_NOTEN                       159
#define IDS_QUANTISIZE_CHORD            159
#define IDD_SELECT_LANGUAGE             160
#define IDS_PRINT                       160
#define IDS_FILE_EMPTY                  161
#define IDS_MASTER_VOLUME               162
#define IDS_NO_ACCESS_TO_FILE           163
#define IDD_VOLUME                      164
#define IDS_FILE_MISSED                 164
#define IDS_NO_START_CHORDLIST_OR_LYRICLIST 165
#define IDD_LINEFEED                    166
#define IDS_NO_END_LIST                 166
#define IDS_OVERFLOW_CHORDS_LYRICS      167
#define IDD_TEMPO                       168
#define IDS_CHORDS_QUANTISIZED          168
#define IDS_ERROR_CHORDFILE             169
#define IDD_EXPR_MVOLUME                170
#define IDS_LYRIC_EVENTS_CHANGED        170
#define IDS_COUNT_IN_DELETED            171
#define IDS_COUNT_IN_INSERTED           172
#define IDI_ICON1                       173
#define IDS_WITH_INSFILE                173
#define IDI_ICON2                       174
#define IDS_REVOICING                   174
#define IDI_ICON3                       175
#define IDS_CHORDS                      175
#define IDI_ICON4                       176
#define IDS_COUNT_IN_DELETE             176
#define IDI_ICON5                       177
#define IDS_COUNT_IN_INSERT             177
#define IDI_ICON6                       178
#define IDS_SYSEXFILE                   178
#define IDI_ICON7                       179
#define IDI_ICON8                       180
#define IDS_NO_START_SYSEXLIST          180
#define IDI_ICON9                       181
#define IDS_WANT_INSERT_SYSEX           181
#define IDI_ICON10                      182
#define IDS_SYSEX_IMPORT_EXPORT         182
#define IDI_ICON11                      183
#define IDS_SELECT_CHANNEL              183
#define IDI_ICON12                      184
#define IDS_OPEN_LYRICFILE              184
#define IDI_ICON13                      185
#define IDS_GLUE_LYRICS                 185
#define IDI_ICON14                      186
#define IDS_CHORDS_LYRICS_IMPORT_EXPORT 186
#define IDI_ICON15                      187
#define IDS_SELECT_CHORDS_LYRICS        187
#define IDI_ICON16                      188
#define IDS_SELECT_IMPORT_EXPORT        188
#define IDD_QUANTISIZE_CHORDS           189
#define IDS_CONTROLLER                  189
#define IDD_RECORD_CHORDS_LYRICS_DLG    190
#define IDS_CHORD_TICKNUMBER            190
#define IDD_PLAY                        191
#define IDS_INSERT_CHORDS               191
#define IDD_CHANGE_SONGNAME             192
#define IDS_INSERT_LYRICS               192
#define IDD_VEL_COMPRESS                193
#define IDS_OPEN_INSDEFFILE             193
#define IDD_REVOICING                   194
#define IDS_XFCHORDSREMOVE              194
#define IDD_INSDEFDLG                   195
#define IDS_LYRICSREMOVE                195
#define IDR_MENU1                       196
#define IDS_REMOVE_WITHOUT_EXPORT       196
#define IDD_START_BEAT                  197
#define IDS_SONGNAME_TITLE              197
#define IDS_COMPOSER                    198
#define IDD_SYSEX_IMPORT_EXPORT_DLG     199
#define IDS_LYRICIST                    199
#define IDD_LYRICS_AT_CHANNEL_NOTES     200
#define IDS_SCORECHAN_TITLE             200
#define IDD_CHORDS_LYRICS_IMPORT_EXPORT_DGL 201
#define IDS_INSERT                      201
#define IDD_CONTROLLER                  202
#define IDS_REMOVE                      202
#define IDD_EXTRAS                      203
#define IDS_EXTRAS                      203
#define IDD_QUICKSTART                  204
#define IDS_QUICKSTART                  204
#define IDD_SCORECHAN                   205
#define IDS_COPYRIGHT                   205
#define IDD_COPYRIGHT                   206
#define IDS_SCORECHAN                   206
#define IDS_NO_START_CHORDS_LYRICS      207
#define IDI_ICON17                      207
#define IDS_SELECTION                   208
#define IDD_EXCHANGE_CHANNELS           208
#define IDS_SELECT_FUNCTION             209
#define IDS_SELECT_DESTINATION_CHANNEL  210
#define IDD_BROWSE                      210
#define IDS_OVERWRITE_DESTINATION_CHANNEL 211
#define IDD_INSDEF_ON_OFF               211
#define IDS_DELETE_CHANNEL              212
#define IDD_CHANGE_KEY                  212
#define IDS_EXCHANGE_CHANNELS           213
#define IDD_SAVE_CHANGES                213
#define IDS_CUT_COPY_CHANNEL            214
#define IDI_ICON18                      214
#define IDS_DOUBLE_CHANNEL              215
#define IDD_QUANTISIZE_LYRICS           215
#define IDS_SELECT_SOURCE_CHANNEL       216
#define IDD_FILE_REVOICING              216
#define IDS_BROWSE_VOICE_FOR_CHANNEL    217
#define IDS_NO_LYRICS_IN_SONG           218
#define IDD_VOICEFILE_REVOICING         218
#define IDS_EXCHANGE_CHANNELS_TOOLTIP   219
#define IDD_VOICEFILE_BROWSE            219
#define IDS_QUANTISIZE_LYRICS           220
#define IDS_UNDO                        221
#define IDS_CONVERT_FOLDER              222
#define IDS_XG_OPTIMIZE_ABORT           223
#define IDD_PASTE_SYSEX                 223
#define IDS_SELECT_VOICEFILE_FOLDER     226
#define IDD_FILL_LYRIC_METHOD           226
#define IDS_STANDARD_REVOICING_TOOLTIP  227
#define IDS_VOICEFILE_REVOICING_TOOLTIP 228
#define IDS_SELECT_VOICEFILE_FOLDER_STRG 229
#define IDS_CURRENT_FOLDER              230
#define IDS_SELECT                      231
#define IDS_ERROR_VOICEFILE             232
#define IDS_BLOCK_USED                  233
#define IDD_TRANSPOSE_DRUMS             233
#define IDS_BAD_SYSEX                   234
#define IDS_WTEXT_SELECT_VOICEFILE      235
#define IDD_VOLUME_METHOD               235
#define IDS_XG_CONVERTED_CONTROLLER_DELETED 236
#define IDD_MASTER_VOLUME               236
#define IDS_NO_DRUMS                    237
#define IDS_REVOICEFILE                 238
#define IDS_NO_START_REVOICELIST        239
#define IDS_REVOICEFILE_REVOICING_TOOLTIP 240
#define IDS_CONTROLLER_PERFORMED        241
#define IDS_REVOICEFILE_ABORT           242
#define IDS_REVOICE_FOLDER              243
#define IDD_EFFEKT_FILTER               244
#define IDS_SOURCE_FOLDER               245
#define IDD_CONTROLLER_EFFECTS          245
#define IDS_DEST_FOLDER                 246
#define IDS_BATCH_PERFORMED             247
#define IDD_CHORDS_LYRICS_EDITOR_DLG    247
#define IDS_REVOICEFILE_BOXTITLE        248
#define IDS_CHECK_EFFECT_INTENSENESS    249
#define IDD_CHORD_LYRIC_DLG             249
#define IDS_CONTROLLER_EFFECTS          250
#define IDD_FILE_ATTRIBUTES             250
#define IDS_EFFECTS                     251
#define IDS_PRINT_FOLDER                252
#define IDD_START_BEAT_FOLDER           252
#define IDS_PRINT_ABORT                 253
#define IDD_MASTER_VOLUME_FOLDER_DLG    253
#define IDS_SOURCE_FOLDER_PRINT         254
#define IDD_MAINVOLUME_EXPRESSION_FOLDER_DLG 254
#define IDS_DEST_FOLDER_PRINT           255
#define IDS_BATCH_RUNNING               256
#define IDD_KBD_EVENTS                  256
#define IDS_DELETE_DRUM                 257
#define IDD_VH_CHANNEL_DLG              257
#define IDS_MORE_CHUNKS                 258
#define IDD_VH_ACT_DEACT                258
#define IDS_LINEFEED                    259
#define IDR_MENU2                       259
#define IDS_CHORD                       260
#define IDD_PREFERENCES                 260
#define IDS_CHORD_LYRIC_EDITOR          261
#define IDD_FILLLYRICS_LINEFEED         261
#define IDS_FILEFORMAT_FOLDER           262
#define IDD_SPECIAL_PREFERENCES         262
#define IDS_FILEFORMAT_ABORT            263
#define IDS_SOURCE_FOLDER_FILEFORMAT    264
#define IDS_YES                         265
#define IDD_SCORE_NOTES_OPT             265
#define IDS_NO                          266
#define IDD_QUANTIZE                    266
#define IDS_TIME                        267
#define IDD_DELETE_SHORT_NOTES          267
#define IDS_NO_MEASURES                 268
#define IDS_DURATION                    269
#define IDD_DELETE_MIDI_EVENTS          269
#define IDS_FILE_DATA                   270
#define IDD_XG_EFFECTDEF_ON_OFF_DLG     270
#define IDS_KEY                         271
#define IDD_EFFECTDEFDLG                271
#define IDS_MORE_CHUNKS_SHORT           272
#define IDS_FILE_FORMAT                 273
#define IDI_ICON19                      273
#define IDS_SAVE_AS                     274
#define IDS_COUNT_IN                    275
#define IDD_DRUMS_DLG                   275
#define IDS_COUNT_IN_FOLDER             276
#define IDD_DRUM_TEMPLATE               276
#define IDS_COUNT_IN_ABORT              277
#define IDS_SOURCE_FOLDER_EXECUTE       278
#define IDD_LENGTHEN                    278
#define IDS_DEST_FOLDER_EXECUTE         279
#define IDD_TIME_SIGNATURE              279
#define IDS_MASTER_VOLUME_FOLDER        280
#define IDI_ICON20                      280
#define IDS_MASTER_VOLUME_ABORT         281
#define IDD_DELETE_FILL_LYRICS          281
#define IDS_MAIN_VOLUME_EXPRESSION_FOLDER 282
#define IDD_CLICK_CHAN                  282
#define IDS_MAIN_VOLUME_EXPRESSION_ABORT 283
#define IDS_VH_CHANNEL                  284
#define IDS_VH_CH                       285
#define IDS_NO_KBD_EVENTS               286
#define IDS_KBD_EVENTS                  287
#define IDS_CHORDS_CHANGED              288
#define IDS_NORMALIZE_CHORDS            289
#define IDS_CHAN_10_NO_DRUMS            290
#define IDD_SCORE                       290
#define IDS_NO_VH_CHANNEL_FOUND         291
#define IDD_SCORE_LAYOUT                291
#define IDS_ACTIVATE_VH_CHANNEL         292
#define IDS_DEACTIVATE_VH_CHANNEL       293
#define IDS_ACT                         294
#define IDS_DEACT                       295
#define IDS_VH_ACT_DEACT_ABORT          296
#define IDS_VH_ACT_DEACT_FOLDER         297
#define IDD_COMPUTE_BANK_LSB_MSB        297
#define IDS_CHANNEL                     298
#define IDD_DIALOG1                     298
#define IDS_MAX_VAL                     299
#define IDS_MAX_VAL_ALL                 300
#define IDS_BANKNAME                    301
#define IDD_DIALOG2                     301
#define IDS_VOICENAME                   302
#define IDS_BROWSE_VOICE                303
#define IDS_REVOICING_SHORT             304
#define IDC_CURSOR1                     304
#define IDS_PLUS_OCTAVE                 305
#define IDS_MUTE                        306
#define IDS_HIGH_LIMIT                  307
#define IDS_LOW_LIMIT                   308
#define IDS_TRANSPOSE_NO                309
#define IDS_DELETE_UPTO                 310
#define IDS_MIN_NEW                     311
#define IDS_MAX_NEW                     312
#define IDS_AVERAGE                     313
#define IDS_DELETE_KBD_EVENTS_ABORT     314
#define IDS_DELETE_KBD_EVENTS_FOLDER    315
#define IDS_PREFERENCES                 316
#define IDS_FILL_LYRICS_LINEFEED        317
#define IDS_INSDEF                      318
#define IDS_SPECIAL_PREFERENCES         319
#define IDS_DONT_LOAD_SOURCE            320
#define IDS_NO_START_SYSEXLIST_MBT      321
#define IDS_WITH_MBT                    322
#define IDS_NO_SCORE_CHANNEL_FOUND      323
#define IDS_SCORE_NOTES_OPT             324
#define IDS_VH_CHAN                     325
#define IDS_MIN_LENGTH                  326
#define IDS_NUMBER                      327
#define IDS_NOTE_AREA                   328
#define IDS_BEFORE_NOTES                329
#define IDS_FILL_LYRIC_FOLDER           330
#define IDS_FILL_LYRIC_ABORT            331
#define IDS_DRUMFOLDER                  332
#define IDS_DRUMFOLDER_ABORT            333
#define IDS_DRUMFILE_BOXTITLE           334
#define IDS_DRUMFILE                    335
#define IDS_NO_START_DRUMLIST           336
#define IDS_NO_COLON                    337
#define IDS_NO_CHAN_NUMBER              338
#define IDS_NO_NOTENAME                 339
#define IDS_DRUMS                       340
#define IDS_CLOSE                       341
#define IDS_DRUMS_DIALOG                342
#define IDS_DRUMS_BATCH                 343
#define IDS_QUANTIZE                    344
#define IDS_DELETE_MIDI_EVENTS          345
#define IDS_DELETE_SHORT_NOTES          346
#define IDS_XG_EFFECTDEF                347
#define IDS_GM_CONVERT_ABORT            348
#define IDS_GM_CONVERT_FOLDER           349
#define IDS_CONVERSION_ACCOMPLISHED     350
#define IDS_CONVERT_GM_TT               351
#define IDS_CONVERSION_NOT_POSSIBLE_META 352
#define IDS_LENGTHEN                    353
#define IDS_MORE_TIME_SIGNATURES        354
#define IDS_TIMEFILE                    355
#define IDS_NO_START_TIMELIST_MBT       356
#define IDS_NO_FL_DELETED               357
#define IDS_DELETE_COUNT_IN             358
#define IDS_DELETE_CHAN_10              359
#define IDS_TIME_SIGNATURE              360
#define IDS_CLICK_CHAN                  362
#define IDS_CLICKS_INSERTED             363
#define IDS_ONLY_NOTEAREA               364
#define IDS_NEWPAGE                     365
#define IDS_LYRICFILE                   366
#define IDS_NO_START_LYRICLIST          367
#define IDS_SYSEX                       368
#define IDS_CONVERSION_NOT_POSSIBLE_CH9 369
#define IDS_SCORELAYOUT_FOLDER          370
#define IDS_SCORELAYOUT_ABORT           371
#define IDS_SCORECHAN_FOLDER            372
#define IDS_SCORECHAN_ABORT             373
#define IDS_SCORE_CHANNELS              374
#define IDS_FILE_DATA_TEXT              375
#define IDS_PLAY_TRANSFORM_MEGAVOICE    376
#define IDS_SELECT_LYRIC_FILE_BEFORE    377
#define IDS_OVERFLOW_LYRICS             378
#define IDC_EVENTS                      1002
#define IDC_RUN                         1004
#define IDC_SELECTALLMETA               1005
#define IDC_SYSEX                       1006
#define IDC_HEXA                        1007
#define IDC_CHORDS                      1008
#define IDC_OPTIONTEXT                  1009
#define IDC_INFO                        1010
#define IDC_COPYRIGHT                   1011
#define IDC_EMAIL                       1012
#define IDC_CHANNEL_SELECT              1015
#define IDC_CH1                         1016
#define IDC_CH2                         1017
#define IDC_CH3                         1018
#define IDC_CH4                         1020
#define IDC_CH5                         1022
#define IDC_CH9                         1023
#define IDC_CH13                        1024
#define IDC_CH6                         1025
#define IDC_CH7                         1026
#define IDC_CH8                         1028
#define IDC_CH10                        1029
#define IDC_CH11                        1030
#define IDC_CH12                        1031
#define IDC_CH14                        1032
#define IDC_CH15                        1033
#define IDC_CH16                        1034
#define IDC_NOTE                        1035
#define IDC_AFTERTOUCH                  1036
#define IDC_CONTROLCHANGE               1037
#define IDC_PROGRAMCHANGE               1038
#define IDC_CHANNELPRESSURE             1039
#define IDC_PITCHWHEEL                  1040
#define IDC_SUMMARY                     1041
#define IDC_SEQUENCENUMBER              1043
#define IDC_TEXT                        1044
#define IDC_SONGSEQUTRACKNAME           1046
#define IDC_INSTRUMENTNAME              1047
#define IDC_MARKER                      1049
#define IDC_CUEPOINT                    1050
#define IDC_CHANNELPREFIX               1051
#define IDC_MIDIPORT                    1052
#define IDC_ENDMTRK                     1053
#define IDC_TIMESIGNATURE               1054
#define IDC_TEMPO                       1055
#define IDC_SMPTEOFFSET                 1056
#define IDC_XF                          1057
#define IDC_KEYSIGNATURE                1058
#define IDC_FILENAME                    1059
#define IDC_SOURCEFILE                  1060
#define IDC_GRUPPEMIDIEVENTS            1061
#define IDC_PROTFILETXT                 1064
#define IDC_PROTFILEWND                 1065
#define IDC_SYSEXGROUP                  1066
#define IDC_VIEW                        1067
#define IDC_METAGRUPPENFELD             1070
#define IDC_GROUPFINDCHORDS             1072
#define IDC_GROUPSUMMARY                1073
#define IDC_SYSEXHEX                    1074
#define IDC_METAHEX                     1075
#define IDC_SELECTSOURCE                1080
#define IDC_CLEAR                       1085
#define IDC_INSDEFFILE                  1087
#define IDC_INSDEF                      1088
#define IDC_SELECTINSDEFFILE            1089
#define IDC_SELECTINSDEF                1090
#define IDC_INSDEFFILENAME              1091
#define IDC_INSDEFNAME                  1092
#define IDC_INSDEFLIST                  1093
#define IDC_TRANSPOSE                   1095
#define IDC_LISTTRANSPOSE_NO            1096
#define IDC_INSERT_CHORDS               1098
#define IDC_PLAY                        1104
#define IDC_STOP                        1106
#define IDC_TEXT_CHANNEL                1108
#define IDC_TEXT_MUTE                   1109
#define IDC_TEXT_HIGH_LIMIT             1110
#define IDC_TEXT_LOW_LIMIT              1111
#define IDC_TEXT_TRANSPOSE_NO           1112
#define IDC_TEXT_1                      1113
#define IDC_TEXT_2                      1114
#define IDC_TEXT_3                      1115
#define IDC_TEXT_4                      1116
#define IDC_TEXT_5                      1117
#define IDC_TEXT_6                      1118
#define IDC_TEXT_7                      1119
#define IDC_TEXT_8                      1120
#define IDC_TEXT_9                      1121
#define IDC_TEXT_10                     1122
#define IDC_TEXT_11                     1123
#define IDC_TEXT_12                     1124
#define IDC_TEXT_13                     1125
#define IDC_TEXT_14                     1126
#define IDC_TEXT_15                     1127
#define IDC_TEXT_16                     1128
#define IDC_CHECK_MUTE1                 1130
#define IDC_EDIT_HL1                    1131
#define IDC_EDIT_LL1                    1132
#define IDC_EDIT_HL2                    1133
#define IDC_CHECK_MUTE2                 1134
#define IDC_CHECK_MUTE3                 1135
#define IDC_CHECK_MUTE4                 1136
#define IDC_CHECK_MUTE5                 1137
#define IDC_CHECK_MUTE6                 1138
#define IDC_CHECK_MUTE7                 1139
#define IDC_CHECK_MUTE8                 1140
#define IDC_CHECK_MUTE9                 1141
#define IDC_CHECK_MUTE10                1142
#define IDC_CHECK_MUTE11                1143
#define IDC_CHECK_MUTE12                1144
#define IDC_CHECK_MUTE13                1145
#define IDC_CHECK_MUTE14                1146
#define IDC_CHECK_MUTE15                1147
#define IDC_CHECK_MUTE16                1148
#define IDC_EDIT_HL3                    1149
#define IDC_EDIT_HL4                    1150
#define IDC_EDIT_LL2                    1151
#define IDC_EDIT_LL3                    1152
#define IDC_EDIT_LL4                    1153
#define IDC_EDIT_HL5                    1154
#define IDC_EDIT_LL5                    1155
#define IDC_EDIT_HL6                    1156
#define IDC_EDIT_LL6                    1157
#define IDC_EDIT_HL7                    1158
#define IDC_EDIT_LL7                    1159
#define IDC_EDIT_HL8                    1160
#define IDC_EDIT_HL9                    1161
#define IDC_EDIT_HL10                   1162
#define IDC_EDIT_HL11                   1163
#define IDC_EDIT_HL12                   1164
#define IDC_EDIT_HL13                   1165
#define IDC_EDIT_HL14                   1166
#define IDC_EDIT_HL16                   1167
#define IDC_EDIT_HL15                   1168
#define IDC_EDIT_LL8                    1169
#define IDC_EDIT_LL9                    1170
#define IDC_EDIT_LL10                   1171
#define IDC_EDIT_LL11                   1172
#define IDC_EDIT_LL12                   1173
#define IDC_EDIT_LL13                   1174
#define IDC_EDIT_LL14                   1175
#define IDC_EDIT_LL15                   1176
#define IDC_EDIT_LL16                   1177
#define IDC_CHECK                       1179
#define IDC_OCT1                        1181
#define IDC_OCT_LIST                    1182
#define IDC_OCT2                        1183
#define IDC_OCT3                        1185
#define IDC_OCT4                        1186
#define IDC_OCT5                        1187
#define IDC_OCT6                        1188
#define IDC_OCT7                        1189
#define IDC_OCT8                        1190
#define IDC_OCT9                        1191
#define IDC_OCT10                       1192
#define IDC_OCT11                       1193
#define IDC_OCT12                       1194
#define IDC_OCT13                       1195
#define IDC_OCT14                       1196
#define IDC_OCT15                       1197
#define IDC_OCT16                       1198
#define IDC_TYPE1                       1199
#define IDC_TYPE2                       1200
#define IDC_TYPE3                       1201
#define IDC_TYPE4                       1202
#define IDC_TYPE5                       1203
#define IDC_TYPE6                       1204
#define IDC_TYPE7                       1205
#define IDC_TYPE8                       1206
#define IDC_TYPE9                       1207
#define IDC_TYPE10                      1208
#define IDC_TYPE11                      1209
#define IDC_TYPE12                      1210
#define IDC_TYPE13                      1211
#define IDC_TYPE14                      1212
#define IDC_TYPE15                      1213
#define IDC_TYPE16                      1214
#define IDC_TYPETEXT                    1215
#define IDC_NOTENBMP                    1218
#define IDC_CHORD_GROUP                 1223
#define IDC_CHORD_NOGROUP               1224
#define IDC_CHORD_PATCH1                1225
#define IDC_CHORD_PATCH2                1226
#define IDC_CHORD_PATCH3                1227
#define IDC_CHORD_PATCH4                1228
#define IDC_CHORD_PATCH5                1229
#define IDC_CHORD_PATCH6                1230
#define IDC_CHORD_PATCH7                1231
#define IDC_CHORD_PATCH8                1232
#define IDC_CHORD_PATCH9                1233
#define IDC_CHORD_PATCH10               1234
#define IDC_CHORD_PATCH11               1235
#define IDC_CHORD_PATCH12               1236
#define IDC_CHORD_PATCH13               1237
#define IDC_CHORD_PATCH14               1238
#define IDC_CHORD_PATCH15               1239
#define IDC_CHORD_PATCH16               1240
#define IDC_CHORD_PATCHALL              1241
#define IDC_PSRUTI_HELP                 1242
#define IDC_LANGUAGE                    1243
#define IDC_SELECT_GERMAN               1244
#define IDC_SELECT_ENGLISH              1245
#define IDC_CHECK_SIMPLE                1246
#define IDC_HOMEPAGE                    1247
#define IDC_TEXT_ZIEL                   1250
#define IDC_EDIT_V9                     1252
#define IDC_EDIT_V1                     1254
#define IDC_EDIT_V2                     1255
#define IDC_EDIT_V3                     1256
#define IDC_EDIT_V4                     1257
#define IDC_EDIT_V5                     1258
#define IDC_EDIT_V6                     1259
#define IDC_EDIT_V7                     1260
#define IDC_EDIT_V8                     1261
#define IDC_MAXVOLUME                   1262
#define IDC_EDIT_V10                    1263
#define IDC_EDIT_V11                    1264
#define IDC_EDIT_V12                    1265
#define IDC_EDIT_V13                    1266
#define IDC_EDIT_V14                    1267
#define IDC_EDIT_V15                    1268
#define IDC_EDIT_V16                    1269
#define IDC_VKANAL                      1270
#define IDC_VK1                         1271
#define IDC_VK16                        1272
#define IDC_VK15                        1273
#define IDC_VK14                        1274
#define IDC_VK13                        1275
#define IDC_VK12                        1276
#define IDC_VK11                        1277
#define IDC_VK10                        1278
#define IDC_VK9                         1279
#define IDC_VK8                         1280
#define IDC_VK7                         1281
#define IDC_VK6                         1282
#define IDC_VK5                         1283
#define IDC_VK4                         1284
#define IDC_VK3                         1285
#define IDC_VK2                         1286
#define IDC_V_VOICE1                    1288
#define IDC_V_VOICE2                    1289
#define IDC_V_VOICE3                    1290
#define IDC_V_VOICE4                    1291
#define IDC_V_VOICE5                    1292
#define IDC_V_VOICE6                    1293
#define IDC_V_VOICE7                    1294
#define IDC_V_VOICE8                    1295
#define IDC_V_VOICE9                    1296
#define IDC_V_VOICE10                   1297
#define IDC_V_VOICE11                   1298
#define IDC_V_VOICE12                   1299
#define IDC_V_VOICE13                   1300
#define IDC_V_VOICE14                   1301
#define IDC_V_VOICE15                   1302
#define IDC_V_VOICE16                   1303
#define IDC_VOICE                       1304
#define IDC_NEW_KEY                     1305
#define IDC_KEYLIST                     1316
#define IDC_MAJMINLIST                  1317
#define IDC_PRINT_CHORDS                1320
#define IDC_SAVE_AS                     1321
#define IDC_GROUPDEST                   1322
#define IDC_GROUPTRANSPOSE              1323
#define IDC_GROUPCHORDS                 1324
#define IDC_GROUPVOLUME                 1325
#define IDC_SELECT_MIDI_DEVICE          1326
#define IDC_CHORDS_FROM_FILE            1327
#define IDC_GROUP_CHRORDS_FROM_FILE     1328
#define IDC_FILLLYRICS                  1330
#define IDC_GROUP_LYRICS                1331
#define IDC_CHECK_BEAT_CHORDS           1332
#define IDC_GROUP_INFRA                 1333
#define IDC_MAXVOLUME_ALL               1334
#define IDC_EDIT_ALL                    1335
#define IDC_PERCENT                     1336
#define IDC_TAKE_IT                     1337
#define IDC_TAKT_LYRIC                  1338
#define IDC_BEAT_LYRIC                  1339
#define IDC_TAKT_LYRIC_TEXT             1340
#define IDC_BEAT_LYRIC_TEXT             1341
#define IDC_LINEFEED_NEWPAGE            1342
#define IDC_GROUP_DEFINE_FILL_LYRICS    1343
#define IDC_GROUP_ALL                   1344
#define IDC_XG_CONVERT                  1345
#define IDC_GROUP_XG_CONVERT            1346
#define IDC_DEFAULT_LYRICS              1347
#define IDC_XG_CHORD_EXPORT             1348
#define IDC_GROUP_XG_CHORDS_EXPORT      1349
#define IDC_CHECK_DELETE_XF_CHORDS      1350
#define IDC_END_LYRIC_TEXT              1351
#define IDC_END_LYRIC                   1352
#define IDC_GROUPTEMPO                  1353
#define IDC_EDIT_PERCENT                1356
#define IDC_TEMPO_TEXT                  1357
#define IDC_EDIT_TEMPO                  1358
#define IDC_PERCENT_CHAR                1359
#define IDC_CHECK_SYSEX_CHORDS          1360
#define IDC_CHECK_INSERT_CHORDS         1361
#define IDC_CHECK_PROT_CHORDS           1362
#define IDC_OK                          1363
#define IDC_FILL_LYRICS                 1365
#define IDC_SYSEX_CHORDS                1366
#define IDC_TAKT_BEAT                   1367
#define IDC_LAST_TAKT_BEAT              1370
#define IDC_LAST_TAKT_TEXT              1371
#define IDC_VOLUME                      1375
#define IDC_EXPR_MVOLUME_GROUP          1376
#define IDC_CHANGE_TO_MVOLUME           1377
#define IDC_CHANGE_TO_EXPRESSION        1378
#define IDC_HP_MIDIFILE_LINK            1379
#define IDC_APPLICATION_TEXT            1380
#define IDC_FILL_LYRICS_GROUP           1381
#define IDC_LINE_FEED_GROUP             1382
#define IDC_SELECT_LINEFEED_CHECK       1385
#define IDC_SELECT_FILL_LYRICS_CHECK    1386
#define IDC_CHORDS_IMPORT_EXPORT        1395
#define IDC_LYRIC_IMPORT_EXPORT         1396
#define IDC_IMPORT_GROUP                1397
#define IDC_EXPORT_GROUP                1398
#define IDC_LYRIC_IMPORT_EXPORT_GROUP   1402
#define IDC_PLAY_BUTTON                 1403
#define IDC_LAST_TKT_BEAT               1409
#define IDC_VON_TEXT                    1410
#define IDC_LYRIC_FRAME                 1411
#define IDC_SLIDER_TEMPO                1412
#define IDC_TEMPO_DISPLAY               1413
#define IDC_DEFAULT_TEMPO               1414
#define IDC_SLIDER_TRANSPOSE            1415
#define IDC_TRANSPOSE_DISPLAY           1416
#define IDC_TRANSPOSE_NAME              1417
#define IDC_DEFAULT_TRANSPOSE           1418
#define IDC_EDIT_NEW_SONGNAME           1420
#define IDC_CHANGE_SONGNAME_GROUP       1421
#define IDC_PRINT                       1422
#define IDC_RECORD_CHORDS               1423
#define IDC_REC_CHORD_LYRIC_TEXT        1425
#define IDC_RECORD_GROUP                1427
#define IDC_TEMPO_GROUP                 1428
#define IDC_PLAY_GROUP                  1429
#define IDC_TRANSPOSE_GROUP             1430
#define IDC_RECORD_OK                   1431
#define IDC_ACTUAL_LYRIC_CHORD          1432
#define IDC_NEXT_LYRIC_CHORD            1433
#define IDC_START_BEAT                  1434
#define IDC_START_BEAT_GROUP            1435
#define IDC_INSERT_CHORDS_LYRICS        1436
#define IDC_QUANTISIZE_TEXT             1438
#define IDC_HALF_NOTE_BUTTON            1439
#define IDC_WHOLE_NOTE_BUTTON           1440
#define IDC_QUARTER_NOTE_BUTTON         1441
#define IDC_EIGHTH_NOTE_BUTTON          1442
#define IDC_BEAT1_QUANTISIZE            1443
#define IDC_BEAT_1_3_QUANTISIZE         1444
#define IDC_BEAT_ALL_QUANTISIZE         1445
#define IDC_QUANTISIZE_CHORDS           1446
#define IDC_QUANTISIZE_CHORDS_GROUP     1447
#define IDC_CHORDS_LYRIC_GROUP          1449
#define IDC_MIDI_GROUP                  1450
#define IDC_VEL_COMPRESS                1451
#define IDC_TXT_CHAN                    1452
#define IDC_TXT_MIN_IST                 1453
#define IDC_TXT_MAX_IST                 1454
#define IDC_TXT_DELETE_UPTO             1456
#define IDC_TXT_MIN_NEW                 1458
#define IDC_TXT_MAX_NEW                 1459
#define IDC_TXT_1                       1460
#define IDC_TXT_2                       1461
#define IDC_TXT_3                       1462
#define IDC_TXT_4                       1463
#define IDC_TXT_5                       1464
#define IDC_TXT_6                       1465
#define IDC_TXT_7                       1466
#define IDC_TXT_8                       1467
#define IDC_TXT_9                       1468
#define IDC_TXT_10                      1469
#define IDC_TXT_11                      1470
#define IDC_TXT_12                      1471
#define IDC_TXT_13                      1472
#define IDC_TXT_14                      1473
#define IDC_TXT_15                      1474
#define IDC_TXT_16                      1475
#define IDC_EDT_MIN1                    1476
#define IDC_EDT_MAX1                    1477
#define IDC_EDT_DELETE_UPTO1            1479
#define IDC_EDT_MIN_NEW1                1481
#define IDC_EDT_MAX_NEW1                1482
#define IDC_EDT_MIN2                    1483
#define IDC_EDT_MAX2                    1484
#define IDC_EDT_DELETE_UPTO2            1486
#define IDC_EDT_MIN_NEW2                1488
#define IDC_EDT_MAX_NEW2                1489
#define IDC_EDT_MIN3                    1490
#define IDC_EDT_MAX3                    1491
#define IDC_EDT_DELETE_UPTO3            1493
#define IDC_EDT_MIN_NEW3                1495
#define IDC_EDT_MAX_NEW3                1496
#define IDC_EDT_MIN4                    1497
#define IDC_EDT_MAX4                    1498
#define IDC_EDT_DELETE_UPTO4            1500
#define IDC_EDT_MIN_NEW4                1502
#define IDC_EDT_MAX_NEW4                1503
#define IDC_EDT_MIN5                    1504
#define IDC_EDT_MAX5                    1505
#define IDC_EDT_DELETE_UPTO5            1507
#define IDC_EDT_MIN_NEW5                1509
#define IDC_EDT_MAX_NEW5                1510
#define IDC_EDT_MIN6                    1511
#define IDC_EDT_MAX6                    1512
#define IDC_EDT_DELETE_UPTO6            1514
#define IDC_EDT_MIN_NEW6                1516
#define IDC_EDT_MAX_NEW6                1517
#define IDC_EDT_MIN7                    1518
#define IDC_EDT_MAX7                    1519
#define IDC_EDT_DELETE_UPTO7            1521
#define IDC_EDT_MIN_NEW7                1523
#define IDC_EDT_MAX_NEW7                1524
#define IDC_EDT_MIN8                    1525
#define IDC_EDT_MAX8                    1526
#define IDC_EDT_DELETE_UPTO8            1528
#define IDC_EDT_MIN_NEW8                1530
#define IDC_EDT_MAX_NEW8                1531
#define IDC_EDT_MIN9                    1532
#define IDC_EDT_MAX9                    1533
#define IDC_EDT_DELETE_UPTO9            1535
#define IDC_EDT_MIN_NEW9                1537
#define IDC_EDT_MAX_NEW9                1538
#define IDC_EDT_MIN10                   1539
#define IDC_EDT_MAX10                   1540
#define IDC_EDT_DELETE_UPTO10           1542
#define IDC_EDT_MIN_NEW10               1544
#define IDC_EDT_MAX_NEW10               1545
#define IDC_EDT_MIN11                   1546
#define IDC_EDT_MAX11                   1547
#define IDC_EDT_DELETE_UPTO11           1549
#define IDC_EDT_MIN_NEW11               1551
#define IDC_EDT_MAX_NEW11               1552
#define IDC_EDT_MIN12                   1553
#define IDC_EDT_MAX12                   1554
#define IDC_EDT_DELETE_UPTO12           1556
#define IDC_EDT_MIN_NEW12               1558
#define IDC_EDT_MAX_NEW12               1559
#define IDC_EDT_MIN13                   1560
#define IDC_EDT_MAX13                   1561
#define IDC_EDT_DELETE_UPTO13           1563
#define IDC_EDT_MIN_NEW13               1565
#define IDC_EDT_MAX_NEW13               1566
#define IDC_EDT_MIN14                   1567
#define IDC_EDT_MAX14                   1568
#define IDC_EDT_DELETE_UPTO14           1570
#define IDC_EDT_MIN_NEW14               1572
#define IDC_EDT_MAX_NEW14               1573
#define IDC_EDT_MIN15                   1574
#define IDC_EDT_MAX15                   1575
#define IDC_EDT_DELETE_UPTO15           1577
#define IDC_EDT_MIN_NEW15               1579
#define IDC_EDT_MAX_NEW15               1580
#define IDC_EDT_MIN16                   1581
#define IDC_EDT_MAX16                   1582
#define IDC_EDT_DELETE_UPTO16           1584
#define IDC_EDT_MIN_NEW16               1586
#define IDC_EDT_MAX_NEW16               1587
#define IDC_TXT_VOICE                   1589
#define IDC_TXT_DEFAULT                 1590
#define IDC_DEFAULT_BUTTON1             1591
#define IDC_DEFAULT_BUTTON2             1592
#define IDC_DEFAULT_BUTTON3             1593
#define IDC_DEFAULT_BUTTON4             1594
#define IDC_DEFAULT_BUTTON5             1595
#define IDC_DEFAULT_BUTTON6             1596
#define IDC_DEFAULT_BUTTON7             1597
#define IDC_DEFAULT_BUTTON8             1598
#define IDC_DEFAULT_BUTTON9             1599
#define IDC_DEFAULT_BUTTON10            1600
#define IDC_DEFAULT_BUTTON11            1601
#define IDC_DEFAULT_BUTTON12            1602
#define IDC_DEFAULT_BUTTON13            1603
#define IDC_DEFAULT_BUTTON14            1604
#define IDC_DEFAULT_BUTTON15            1605
#define IDC_DEFAULT_BUTTON16            1606
#define IDC_EDT_VOICE1                  1607
#define IDC_EDT_VOICE2                  1608
#define IDC_EDT_VOICE3                  1609
#define IDC_EDT_VOICE4                  1610
#define IDC_EDT_VOICE5                  1611
#define IDC_EDT_VOICE6                  1612
#define IDC_EDT_VOICE7                  1613
#define IDC_EDT_VOICE8                  1614
#define IDC_EDT_VOICE9                  1615
#define IDC_EDT_VOICE10                 1616
#define IDC_EDT_VOICE11                 1617
#define IDC_EDT_VOICE12                 1618
#define IDC_EDT_VOICE13                 1619
#define IDC_EDT_VOICE14                 1620
#define IDC_EDT_VOICE15                 1621
#define IDC_EDT_VOICE16                 1622
#define IDC_CHECK_ALL                   1623
#define IDC_CHORD_NO1                   1624
#define IDC_CHORD_NO2                   1625
#define IDC_CHORD_NO3                   1626
#define IDC_CHORD_NO4                   1627
#define IDC_CHORD_NO5                   1628
#define IDC_CHORD_NO6                   1629
#define IDC_CHORD_NO7                   1630
#define IDC_CHORD_NO8                   1631
#define IDC_CHORD_NO9                   1632
#define IDC_CHORD_NO10                  1633
#define IDC_CHORD_NO11                  1634
#define IDC_CHORD_NO12                  1635
#define IDC_CHORD_NO13                  1636
#define IDC_CHORD_NO14                  1637
#define IDC_CHORD_NO15                  1638
#define IDC_CHORD_NO16                  1639
#define IDC_CHORD_NOALL                 1640
#define IDC_REVOICING                   1641
#define IDC_CHANNELTXT                  1642
#define IDC_BANK                        1643
#define IDC_BANKNUMBER                  1643
#define IDC_VOICETXT                    1644
#define IDC_MSBTXT                      1645
#define IDC_LSBTXT                      1646
#define IDC_BANKNAMETXT                 1647
#define IDC_VOICENOTXT                  1648
#define IDC_VOICENAMETXT                1649
#define IDC_EDIT1                       1650
#define IDC_START_BEAT_VEL              1650
#define IDC_LFLYRIC_TICKS               1650
#define IDC_EDIT_NEW_COMPOSER           1650
#define IDC_EDIT_COPYRIGHT              1650
#define IDC_SLIDER_TIME_POS             1650
#define IDC_SEARCH_STRING               1650
#define IDC_COMPUTED_KEY                1650
#define IDC_VOICEFILE_FOLDER            1650
#define IDC_PASTE_EDIT                  1650
#define IDC_EDIT_VELOCITY               1650
#define IDC_EDIT_MASTER_VOLUME          1650
#define IDC_CHORD_POS                   1650
#define IDC_ACT_TYPE                    1650
#define IDC_FILE_ATTRIBUTES             1650
#define C_ON_ALL_BEATS_TEXT             1650
#define IDC_MASTER_VOLUM_EDIT           1650
#define IDC_VH_ACT_DEACT                1650
#define IDC_MIDI_PORT                   1650
#define IDC_MEASURE                     1650
#define IDC_WHOLE_TXT                   1650
#define IDC_SELECT_CHAN                 1650
#define IDC_TIME                        1650
#define IDC_FL1                         1650
#define IDC_DRUM_MAINVOLUME             1650
#define IDC_VELOCITY                    1650
#define IDC_EDIT_MSB                    1650
#define IDC_1TXT                        1651
#define IDC_2TXT                        1652
#define IDC_3TXT                        1653
#define IDC_4TXT                        1654
#define IDC_5TXT                        1655
#define IDC_6TXT                        1656
#define IDC_7TXT                        1657
#define IDC_8TXT                        1658
#define IDC_9TXT                        1659
#define IDC_10TXT                       1660
#define IDC_11TXT                       1661
#define IDC_12TXT                       1662
#define IDC_13TXT                       1663
#define IDC_14TXT                       1664
#define IDC_15TXT                       1665
#define IDC_16TXT                       1666
#define IDC_INSDEFTXT                   1667
#define IDC_BANKNAME1                   1668
#define IDC_BANKNO1                     1669
#define IDC_VOICENO1                    1670
#define IDC_VOICENAME1                  1671
#define IDC_BANKNAME2                   1672
#define IDC_BANKNO2                     1673
#define IDC_VOICENO2                    1674
#define IDC_VOICENAME2                  1675
#define IDC_BANKNAME3                   1676
#define IDC_BANKNO3                     1677
#define IDC_VOICENO3                    1678
#define IDC_VOICENAME3                  1679
#define IDC_BANKNAME4                   1680
#define IDC_BANKNO4                     1681
#define IDC_VOICENO4                    1682
#define IDC_VOICENAME4                  1683
#define IDC_BANKNAME5                   1688
#define IDC_BANKNO5                     1689
#define IDC_VOICENO5                    1690
#define IDC_VOICENAME5                  1691
#define IDC_BANKNAME6                   1692
#define IDC_BANKNO6                     1693
#define IDC_VOICENO6                    1694
#define IDC_VOICENAME6                  1695
#define IDC_BANKNAME7                   1696
#define IDC_BANKNO7                     1697
#define IDC_VOICENO7                    1698
#define IDC_VOICENAME7                  1699
#define IDC_BANKNAME8                   1700
#define IDC_BANKNO8                     1701
#define IDC_VOICENO8                    1702
#define IDC_VOICENAME8                  1703
#define IDC_BANKNAME9                   1704
#define IDC_BANKNO9                     1705
#define IDC_VOICENO9                    1706
#define IDC_VOICENAME9                  1707
#define IDC_BANKNAME10                  1708
#define IDC_BANKNO10                    1709
#define IDC_VOICENO10                   1710
#define IDC_VOICENAME10                 1711
#define IDC_BANKNAME11                  1712
#define IDC_BANKNO11                    1713
#define IDC_VOICENO11                   1714
#define IDC_VOICENAME11                 1715
#define IDC_BANKNAME12                  1716
#define IDC_BANKNO12                    1717
#define IDC_VOICENO12                   1718
#define IDC_VOICENAME12                 1719
#define IDC_BANKNAME13                  1720
#define IDC_BANKNO13                    1721
#define IDC_VOICENO13                   1722
#define IDC_VOICENAME13                 1723
#define IDC_BANKNAME14                  1724
#define IDC_BANKNO14                    1725
#define IDC_VOICENO14                   1726
#define IDC_VOICENAME14                 1727
#define IDC_BANKNAME15                  1728
#define IDC_BANKNO15                    1729
#define IDC_VOICENO15                   1730
#define IDC_VOICENAME15                 1731
#define IDC_BANKNAME16                  1732
#define IDC_BANKNO16                    1733
#define IDC_VOICENO16                   1734
#define IDC_VOICENAME16                 1735
#define IDC_INSDEFCOMBOBOX              1736
#define IDC_TRANSPOSE_CHORDS_CHECK      1737
#define IDC_VEL_TXT                     1738
#define IDC_START_BEAT_INS_DEL          1739
#define IDC_LFLYRIC_CHECK               1740
#define IDC_TICKS_TXT                   1741
#define IDC_DRUM_TEXT                   1742
#define IDC_DRUM_LIST                   1743
#define IDC_UNDO                        1744
#define IDC_MISC_GROUP                  1745
#define IDC_SYSEX_IMPORT_GROUP          1747
#define IDC_SYSEX_EXPORT_GROUP          1748
#define IDC_SELECT_SYSEX_FILE_IMPORT_CHECK 1749
#define IDC_SYSEX_DELETE_CHECK          1750
#define IDC_SELECT_SYSEX_EXPORT_CHECK   1751
#define IDC_SYSEX_IMPORT_EXPORT_GROUP   1752
#define IDC_LYRICS_AT_CHANNEL_NOTES     1753
#define IDC_CHANNEL_TEXT                1754
#define IDC_VOICE_TEXT                  1755
#define IDC_VOICE1                      1756
#define IDC_VOICE2                      1757
#define IDC_VOICE3                      1758
#define IDC_VOICE4                      1759
#define IDC_VOICE5                      1760
#define IDC_VOICE6                      1761
#define IDC_VOICE7                      1762
#define IDC_VOICE8                      1763
#define IDC_VOICE9                      1764
#define IDC_VOICE10                     1765
#define IDC_VOICE11                     1766
#define IDC_VOICE12                     1767
#define IDC_VOICE13                     1768
#define IDC_VOICE14                     1769
#define IDC_VOICE15                     1770
#define IDC_VOICE16                     1771
#define IDC_CHECK_CHAN1                 1772
#define IDC_CHECK_CHAN2                 1773
#define IDC_CHECK_CHAN3                 1774
#define IDC_CHECK_CHAN4                 1775
#define IDC_CHECK_CHAN5                 1776
#define IDC_CHECK_CHAN6                 1777
#define IDC_CHECK_CHAN7                 1778
#define IDC_CHECK_CHAN8                 1779
#define IDC_CHECK_CHAN9                 1780
#define IDC_CHECK_CHAN10                1781
#define IDC_CHECK_CHAN11                1782
#define IDC_CHECK_CHAN12                1783
#define IDC_CHECK_CHAN13                1784
#define IDC_CHECK_CHAN14                1785
#define IDC_CHECK_CHAN15                1786
#define IDC_CHECK_CHAN16                1787
#define IDC_1_TEXT                      1789
#define IDC_2_TEXT                      1790
#define IDC_3_TEXT                      1791
#define IDC_4_TEXT                      1792
#define IDC_5_TEXT                      1793
#define IDC_6_TEXT                      1794
#define IDC_7_TEXT                      1795
#define IDC_8_TEXT                      1796
#define IDC_9_TEXT                      1797
#define IDC_10_TEXT                     1798
#define IDC_11_TEXT                     1799
#define IDC_12_TEXT                     1800
#define IDC_13_TEXT                     1801
#define IDC_14_TEXT                     1802
#define IDC_15_TEXT                     1803
#define IDC_16_TEXT                     1804
#define IDC_OPEN_LYRIC_FILE             1805
#define IDC_CHORDS_LYRICS_IMPORT_EXPORT 1806
#define IDC_CHORD_CHECK                 1807
#define IDC_LYRIC_CHECK                 1808
#define IDC_CHECK_INSERT_FILL_LYRICS    1809
#define IDC_CHECK_CHORD_SYSEX           1810
#define IDC_CHECK_SELECT_IMPORT         1811
#define IDC_CHECK_REMOVE_AFTER          1812
#define IDC_CHECK_SELECT_EXPORT         1813
#define IDC_CONTROLLER                  1814
#define IDC_EFFECTCOMBOBOX              1815
#define IDC_EXTRAS                      1816
#define IDC_SONGNAME                    1817
#define IDC_SCORECHAN                   1821
#define IDC_QUICKSTART                  1822
#define IDC_SONGNAME_TEXT               1823
#define IDC_COMPOSER_TEXT               1824
#define IDC_LYRICIST_TEXT               1825
#define IDC_EDIT_NEW_LYRICIST           1826
#define IDC_INSERT_REMOVE               1827
#define IDC_LIST_SCORECHAN              1828
#define IDC_SCORE_REMOVE                1829
#define IDC_SCORE_PATCH1                1830
#define IDC_SCORE_PATCH2                1831
#define IDC_SCORE_PATCH3                1832
#define IDC_SCORE_PATCH4                1833
#define IDC_SCORE_PATCH5                1834
#define IDC_SCORE_PATCH6                1835
#define IDC_SCORE_PATCH7                1836
#define IDC_SCORE_PATCH8                1837
#define IDC_SCORE_PATCH9                1838
#define IDC_SCORE_PATCH10               1839
#define IDC_SCORE_PATCH11               1840
#define IDC_SCORE_PATCH12               1841
#define IDC_SCORE_PATCH13               1842
#define IDC_SCORE_PATCH14               1843
#define IDC_SCORE_PATCH15               1844
#define IDC_SCORE_PATCH16               1845
#define IDC_TAKE_IT_TEXT                1846
#define IDC_CUEPOINT_LYRC               1847
#define IDC_SELECT_CUEPOINT_LYRC        1848
#define IDC_EDIT_LYRC_TICKS             1849
#define IDC_LYRC_TICKS_TEXT             1851
#define IDC_SLIDER_TIME                 1852
#define IDC_CHECK_CHAN_1                1853
#define IDC_CHECK_CHAN_2                1854
#define IDC_CHECK_CHAN_3                1855
#define IDC_CHECK_CHAN_4                1856
#define IDC_CHECK_CHAN_5                1857
#define IDC_CHECK_CHAN_6                1858
#define IDC_CHECK_CHAN_7                1859
#define IDC_CHECK_CHAN_8                1860
#define IDC_CHECK_CHAN_9                1861
#define IDC_CHECK_CHAN_10               1862
#define IDC_CHECK_CHAN_11               1863
#define IDC_CHECK_CHAN_12               1864
#define IDC_CHECK_CHAN_13               1865
#define IDC_CHECK_CHAN_14               1866
#define IDC_CHECK_CHAN_15               1867
#define IDC_CHECK_CHAN_16               1868
#define IDC_CHECK_CHAN_ALL              1869
#define IDC_EXCHANGE_CHANNELS           1870
#define IDC_LIST_COPY_EXCHANGE          1872
#define IDC_SOURCE_CHANNEL              1873
#define IDC_DEST_CHANNEL                1874
#define IDC_SOURCE_1                    1875
#define IDC_SOURCE_2                    1876
#define IDC_SOURCE_3                    1877
#define IDC_SOURCE_4                    1878
#define IDC_SOURCE_5                    1879
#define IDC_SOURCE_6                    1880
#define IDC_SOURCE_7                    1881
#define IDC_SOURCE_8                    1882
#define IDC_SOURCE_9                    1883
#define IDC_SOURCE_10                   1884
#define IDC_SOURCE_11                   1885
#define IDC_SOURCE_12                   1886
#define IDC_SOURCE_13                   1887
#define IDC_SOURCE_14                   1888
#define IDC_SOURCE_15                   1889
#define IDC_SOURCE_16                   1890
#define IDC_DEST_1                      1891
#define IDC_DEST_2                      1892
#define IDC_DEST_3                      1893
#define IDC_DEST_4                      1894
#define IDC_DEST_5                      1895
#define IDC_DEST_6                      1896
#define IDC_DEST_7                      1897
#define IDC_DEST_8                      1898
#define IDC_DEST_9                      1899
#define IDC_DEST_10                     1900
#define IDC_DEST_11                     1901
#define IDC_DEST_12                     1902
#define IDC_DEST_13                     1903
#define IDC_DEST_14                     1904
#define IDC_DEST_15                     1905
#define IDC_DEST_16                     1906
#define IDC_CHANNEL_PATCH_1             1907
#define IDC_CHANNEL_PATCH_2             1908
#define IDC_CHANNEL_PATCH_3             1909
#define IDC_CHANNEL_PATCH_4             1910
#define IDC_CHANNEL_PATCH_5             1911
#define IDC_CHANNEL_PATCH_6             1912
#define IDC_CHANNEL_PATCH_7             1913
#define IDC_CHANNEL_PATCH_8             1914
#define IDC_CHANNEL_PATCH_9             1915
#define IDC_CHANNEL_PATCH_10            1916
#define IDC_CHANNEL_PATCH_11            1917
#define IDC_CHANNEL_PATCH_12            1918
#define IDC_CHANNEL_PATCH_13            1919
#define IDC_CHANNEL_PATCH_14            1920
#define IDC_CHANNEL_PATCH_15            1921
#define IDC_CHANNEL_PATCH_16            1922
#define IDC_EINS_TEXT                   1923
#define IDC_ZWEI_TEXT                   1924
#define IDC_DREI_TEXT                   1925
#define IDC_VIER_TEXT                   1926
#define IDC_FUENF_TEXT                  1927
#define IDC_SECHS_TEXT                  1928
#define IDC_SIEBEN_TEXT                 1929
#define IDC_ACHT_TEXT                   1930
#define IDC_NEUN_TEXT                   1931
#define IDC_ZEHN_TEXT                   1932
#define IDC_ELF_TEXT                    1933
#define IDC_ZWOELF_TEXT                 1934
#define IDC_DREIZEHN_TEXT               1935
#define IDC_VIERZEHN_TEXT               1936
#define IDC_FUENFZEHN_TEXT              1937
#define IDC_SECHZEHN_TEXT               1938
#define IDC_CHECK_EINS                  1939
#define IDC_CHECK_ZWEI                  1940
#define IDC_CHECK_DREI                  1941
#define IDC_CHECK_VIER                  1942
#define IDC_CHECK_FUENF                 1943
#define IDC_CHECK_SECHS                 1944
#define IDC_CHECK_SIEBEN                1945
#define IDC_CHECK_ACHT                  1946
#define IDC_CHECK_NEUN                  1947
#define IDC_CHECK_ZEHN                  1948
#define IDC_CHECK_ELF                   1949
#define IDC_CHECK_ZWOELF                1950
#define IDC_CHECK_DREIZEHN              1951
#define IDC_CHECK_VIERZEHN              1952
#define IDC_CHECK_FUENFZEHN             1953
#define IDC_CHECK_SECHZEHN              1954
#define IDC_V1                          1955
#define IDC_V2                          1956
#define IDC_V3                          1957
#define IDC_V4                          1958
#define IDC_V5                          1959
#define IDC_V6                          1960
#define IDC_V7                          1961
#define IDC_V8                          1962
#define IDC_V9                          1963
#define IDC_V10                         1964
#define IDC_V11                         1965
#define IDC_V12                         1966
#define IDC_V13                         1967
#define IDC_V14                         1968
#define IDC_V15                         1969
#define IDC_V16                         1970
#define IDC_LIST_SCORECHAN_RIGHT        1971
#define IDC_LEFT_TEXT                   1972
#define IDC_RIGHT_TEXT                  1973
#define IDC_VOICE_BROWSE1               1974
#define IDC_VOICE_BROWSE2               1975
#define IDC_VOICE_BROWSE3               1976
#define IDC_VOICE_BROWSE4               1977
#define IDC_VOICE_BROWSE5               1978
#define IDC_VOICE_BROWSE6               1979
#define IDC_VOICE_BROWSE7               1980
#define IDC_VOICE_BROWSE8               1981
#define IDC_VOICE_BROWSE9               1982
#define IDC_VOICE_BROWSE10              1983
#define IDC_VOICE_BROWSE11              1984
#define IDC_VOICE_BROWSE12              1985
#define IDC_VOICE_BROWSE13              1986
#define IDC_VOICE_BROWSE14              1987
#define IDC_VOICE_BROWSE15              1988
#define IDC_VOICE_BROWSE16              1989
#define IDC_BROWSE_TEXT                 1990
#define IDC_BROWSE_LIST                 1992
#define IDC_INSDEF_OFF                  1993
#define IDC_CHANGE_KEY                  1994
#define IDC_COMPUTED_KEY_TEXT           1995
#define IDC_NEW_KEY_TEXT                1996
#define IDC_SAVE_NO                     1997
#define IDC_SAVE_CHANGES_TEXT           1998
#define IDC_QUARTER_QUANTISIZE          1999
#define IDC_EIGHTH_QUANTISIZE           2000
#define IDC_SIXTEENTH_QUANTISIZIE       2001
#define IDC_QUANTISIZE_LYRICS           2002
#define IDC_CHECK_PLAY_ALL              2003
#define IDC_ALL_TEXT                    2004
#define IDC_LYRICS_AT_CHORDS            2005
#define IDC_VOICEFILE_REVOICING         2006
#define IDC_REVOICETXT                  2008
#define IDC_BROWSETXT                   2009
#define IDC_REVOICE1                    2012
#define IDC_REVOICE2                    2013
#define IDC_REVOICE3                    2014
#define IDC_REVOICE4                    2015
#define IDC_REVOICE5                    2016
#define IDC_REVOICE6                    2017
#define IDC_REVOICE7                    2018
#define IDC_REVOICE8                    2019
#define IDC_REVOICE9                    2020
#define IDC_REVOICE10                   2021
#define IDC_REVOICE11                   2022
#define IDC_REVOICE12                   2023
#define IDC_REVOICE13                   2024
#define IDC_REVOICE14                   2025
#define IDC_REVOICE15                   2026
#define IDC_REVOICE16                   2027
#define IDC_SEARCH_STRG                 2028
#define IDC_SELECT_FOLDER               2030
#define IDC_BLOCK_LIST                  2031
#define IDC_BLOCK_TEXT                  2032
#define IDC_EFF_BLOCK_TEXT              2033
#define IDC_BLOCK_CHAN1                 2034
#define IDC_BLOCK_CHAN2                 2035
#define IDC_BLOCK_CHAN3                 2036
#define IDC_BLOCK_CHAN4                 2037
#define IDC_BLOCK_CHAN5                 2038
#define IDC_BLOCK_CHAN6                 2039
#define IDC_BLOCK_CHAN7                 2040
#define IDC_BLOCK_CHAN8                 2041
#define IDC_BLOCK_CHAN9                 2042
#define IDC_BLOCK_CHAN10                2043
#define IDC_BLOCK_CHAN11                2044
#define IDC_BLOCK_CHAN12                2045
#define IDC_BLOCK_CHAN13                2046
#define IDC_BLOCK_CHAN14                2047
#define IDC_BLOCK_CHAN15                2048
#define IDC_BLOCK_CHAN16                2049
#define IDC_SELECT_SYSEX_PASTE_IMPORT_CHECK 2050
#define IDC_NOT_AT_LYRICS               2052
#define IDC_NOT_AT_BEATS_WITH_LYRICS    2053
#define IDC_NOT_AT_MEASURES_WITH_LYRICS 2054
#define IDC_TRANSPOSE_MELODY            2055
#define IDC_DRUM_NOTES                  2056
#define IDC_DRUM_CHAN_LIST              2059
#define IDC_DRUMCHANNEL_TXT             2060
#define IDC_SOURCE_NOTE_LIST            2061
#define IDC_DRUM_NOTE_TEXT              2062
#define IDC_NEW_NOTE_LIST               2063
#define IDC_NEW_DRUM_TEXT               2064
#define IDC_VELOCITY_TEXT               2065
#define IDC_FRAME_INSDEF                2066
#define IDC_CHECK_ALL_BEATS             2067
#define IDC_ON_ALL_BEATS_TEXT           2068
#define IDC_EXPRESSION_MAINVOLUME       2069
#define IDC_MASTER_VOLUME               2070
#define IDC_MASTER_VOLUME_TEXT          2072
#define IDC_REVOICE_FILE                2073
#define IDC_CHANNEL                     2074
#define IDC_CTRL91                      2075
#define IDC_CTRL93                      2076
#define IDC_CTRL94                      2077
#define IDC_DRYWET                      2078
#define IDC_TEXT1                       2079
#define IDC_TEXT2                       2080
#define IDC_TEXT3                       2081
#define IDC_TEXT4                       2082
#define IDC_TEXT5                       2083
#define IDC_TEXT6                       2084
#define IDC_TEXT7                       2085
#define IDC_TEXT8                       2086
#define IDC_TEXT9                       2087
#define IDC_TEXT10                      2088
#define IDC_TEXT11                      2089
#define IDC_TEXT12                      2090
#define IDC_TEXT13                      2091
#define IDC_TEXT14                      2092
#define IDC_TEXT15                      2093
#define IDC_TEXT16                      2094
#define IDC_REVERB_1                    2095
#define IDC_REVERB_2                    2096
#define IDC_REVERB_3                    2097
#define IDC_REVERB_4                    2098
#define IDC_REVERB_5                    2099
#define IDC_REVERB_6                    2100
#define IDC_REVERB_7                    2101
#define IDC_REVERB_8                    2102
#define IDC_REVERB_9                    2103
#define IDC_REVERB_10                   2104
#define IDC_REVERB_11                   2105
#define IDC_REVERB_12                   2106
#define IDC_REVERB_13                   2107
#define IDC_REVERB_14                   2108
#define IDC_REVERB_15                   2109
#define IDC_REVERB_16                   2110
#define IDC_CHORUS_1                    2111
#define IDC_CHORUS_2                    2112
#define IDC_CHORUS_3                    2113
#define IDC_CHORUS_4                    2114
#define IDC_CHORUS_5                    2115
#define IDC_CHORUS_6                    2116
#define IDC_CHORUS_7                    2117
#define IDC_CHORUS_8                    2118
#define IDC_CHORUS_9                    2119
#define IDC_CHORUS_10                   2120
#define IDC_CHORUS_11                   2121
#define IDC_CHORUS_12                   2122
#define IDC_CHORUS_13                   2123
#define IDC_CHORUS_14                   2124
#define IDC_CHORUS_15                   2125
#define IDC_CHORUS_16                   2126
#define IDC_VARIATION_1                 2127
#define IDC_VARIATION_2                 2128
#define IDC_VARIATION_3                 2129
#define IDC_VARIATION_4                 2130
#define IDC_VARIATION_5                 2131
#define IDC_VARIATION_6                 2132
#define IDC_VARIATION_7                 2133
#define IDC_VARIATION_8                 2134
#define IDC_VARIATION_9                 2135
#define IDC_VARIATION_10                2136
#define IDC_VARIATION_11                2137
#define IDC_VARIATION_12                2138
#define IDC_VARIATION_13                2139
#define IDC_VARIATION_14                2140
#define IDC_VARIATION_15                2141
#define IDC_VARIATION_16                2142
#define IDC_DRYWET_1                    2143
#define IDC_DRYWET_2                    2144
#define IDC_DRYWET_3                    2145
#define IDC_DRYWET_4                    2146
#define IDC_DRYWET_5                    2147
#define IDC_DRYWET_6                    2148
#define IDC_DRYWET_7                    2149
#define IDC_DRYWET_8                    2150
#define IDC_DRYWET_9                    2151
#define IDC_DRYWET_10                   2152
#define IDC_DRYWET_11                   2153
#define IDC_DRYWET_12                   2154
#define IDC_DRYWET_13                   2155
#define IDC_DRYWET_14                   2156
#define IDC_DRYWET_15                   2157
#define IDC_DRYWET_16                   2158
#define IDC_DRYWET_TEXT_1               2159
#define IDC_DRYWET_TEXT_2               2160
#define IDC_DRYWET_TEXT_3               2161
#define IDC_DRYWET_TEXT_4               2162
#define IDC_DRYWET_TEXT_5               2163
#define IDC_DRYWET_TEXT_6               2164
#define IDC_DRYWET_TEXT_7               2165
#define IDC_DRYWET_TEXT_8               2166
#define IDC_DRYWET_TEXT_9               2167
#define IDC_DRYWET_TEXT_10              2168
#define IDC_DRYWET_TEXT_11              2169
#define IDC_DRYWET_TEXT_12              2170
#define IDC_DRYWET_TEXT_13              2171
#define IDC_DRYWET_TEXT_14              2172
#define IDC_DRYWET_TEXT_15              2173
#define IDC_DRYWET_TEXT_16              2174
#define IDC_EFFECTS                     2175
#define IDC_VOICE_1                     2176
#define IDC_VOICE_2                     2177
#define IDC_VOICE_3                     2178
#define IDC_VOICE_4                     2179
#define IDC_VOICE_5                     2180
#define IDC_VOICE_6                     2181
#define IDC_VOICE_7                     2182
#define IDC_VOICE_8                     2183
#define IDC_VOICE_9                     2184
#define IDC_VOICE_10                    2185
#define IDC_VOICE_11                    2186
#define IDC_VOICE_12                    2187
#define IDC_VOICE_13                    2188
#define IDC_VOICE_14                    2189
#define IDC_VOICE_15                    2190
#define IDC_VOICE_16                    2191
#define IDC_VOICE_TEST1                 2192
#define IDC_VOICE_TEST2                 2193
#define IDC_VOICE_TEST3                 2194
#define IDC_VOICE_TEST4                 2195
#define IDC_VOICE_TEST5                 2196
#define IDC_VOICE_TEST6                 2197
#define IDC_VOICE_TEST7                 2198
#define IDC_VOICE_TEST8                 2199
#define IDC_VOICE_TEST9                 2200
#define IDC_VOICE_TEST10                2201
#define IDC_VOICE_TEST11                2202
#define IDC_VOICE_TEST12                2203
#define IDC_VOICE_TEST13                2204
#define IDC_VOICE_TEST14                2205
#define IDC_VOICE_TEST15                2206
#define IDC_VOICE_TEST16                2207
#define IDC_VOICE_TEST                  2208
#define IDC_NEW_VELOCITY                2209
#define IDC_VELOCITY_MIN                2210
#define IDC_VEL_MIN                     2211
#define IDC_VEL_MAX                     2212
#define IDC_VELOCITY_MAX                2213
#define IDC_CHECK_DYN_VEL               2214
#define IDC_SHIFT_LINEFEEDS             2215
#define IDC_SHIFT_TICKS                 2216
#define IDC_TICKS_TEXT                  2217
#define IDC_CHECK_PROT_CHORDS_LYRIC     2218
#define IDC_CHECK_SELECT_LYRIC_CHORDS   2219
#define IDC_CHORD_CHANNELS_TXT          2220
#define IDC_BASS_CHANNEL_TXT            2221
#define IDC_CHECK_BASS1                 2222
#define IDC_CHECK_BASS2                 2223
#define IDC_CHECK_BASS3                 2224
#define IDC_CHECK_BASS4                 2225
#define IDC_CHECK_BASS5                 2226
#define IDC_CHECK_BASS6                 2227
#define IDC_CHECK_BASS7                 2228
#define IDC_CHECK_BASS8                 2229
#define IDC_CHECK_BASS9                 2230
#define IDC_CHECK_BASS10                2231
#define IDC_CHECK_BASS11                2232
#define IDC_CHECK_BASS12                2233
#define IDC_CHECK_BASS13                2234
#define IDC_CHECK_BASS14                2235
#define IDC_CHECK_BASS15                2236
#define IDC_CHECK_BASS16                2237
#define IDC_SINGLE_CHORDS_TXT           2238
#define IDC_TEST_TXT                    2239
#define IDC_TEST_CHAN1                  2240
#define IDC_TEST_CHAN2                  2241
#define IDC_TEST_CHAN3                  2242
#define IDC_TEST_CHAN4                  2243
#define IDC_TEST_CHAN5                  2244
#define IDC_TEST_CHAN6                  2245
#define IDC_TEST_CHAN7                  2246
#define IDC_TEST_CHAN8                  2247
#define IDC_TEST_CHAN9                  2248
#define IDC_TEST_CHAN10                 2249
#define IDC_TEST_CHAN11                 2250
#define IDC_TEST_CHAN12                 2251
#define IDC_TEST_CHAN13                 2252
#define IDC_TEST_CHAN14                 2253
#define IDC_TEST_CHAN15                 2254
#define IDC_TEST_CHAN16                 2255
#define IDC_CHORDS_LYRICS_EDITOR        2256
#define IDC_EDIT_SLIDER_POS             2257
#define IDC_RGN_FRAME                   2258
#define IDC_RGN_SLIDER                  2259
#define IDC_TIME_TEXT                   2261
#define IDC_CHORD_LYRIC_TEXT            2263
#define IDC_DELETE                      2264
#define IDC_TAKT_BEAT_TICK_TXT          2265
#define IDC_TAKT_BEAT_TICK              2267
#define IDC_EDIT_PLAY                   2268
#define IDC_EDIT_STOP                   2269
#define IDC_EDIT_SLIDER_TIME            2270
#define IDC_EDIT_TIME_TEXT              2271
#define IDC_EDIT_TEMPO_DISPLAY          2273
#define IDC_EDIT_DEFAULT_TEMPO          2274
#define IDC_EDIT_SLIDER_TEMPO           2276
#define IDC_SHIFT_LINEFEEDS_AT          2277
#define IDC_SHIFT_TICKS_AT              2278
#define IDC_TICKS_TEXT_AT               2279
#define IDC_USER_FILL_LYRICS            2280
#define IDC_USER1_FILL_LYRICS           2280
#define IDC_CHORD_LYRIC_PASTE_FRAME     2281
#define IDC_CHORD_LYRIC_SYLLABLE        2283
#define IDC_BUTTON1                     2284
#define IDC_SAVE                        2284
#define IDC_INIT_ZOOM                   2284
#define IDC_EXIT                        2284
#define IDC_DELETE_KBD_EVENTS           2284
#define IDC_FILL_LYRICS_LINEFEED        2284
#define IDC_DEFAULT                     2284
#define IDC_CANCEL                      2284
#define IDC_ON                          2284
#define IDC_EIGHTH_TRIOLE_QUANTISIZE    2284
#define IDC_CHANGE_DRUMS_DIALOG         2284
#define IDC_MSB_LSB_BANK                2284
#define IDC_CALCULATE                   2284
#define IDC_FILE_FORMAT                 2285
#define IDC_PLUS_CTRL                   2286
#define IDC_CTRL1                       2287
#define IDC_CTRL2                       2288
#define IDC_CTRL3                       2289
#define IDC_CTRL4                       2290
#define IDC_CTRL5                       2291
#define IDC_CTRL6                       2292
#define IDC_CTRL7                       2293
#define IDC_CTRL8                       2294
#define IDC_CTRL9                       2295
#define IDC_CTRL10                      2296
#define IDC_CTRL11                      2297
#define IDC_CTRL12                      2298
#define IDC_CTRL13                      2299
#define IDC_CTRL14                      2300
#define IDC_CTRL15                      2301
#define IDC_CTRL16                      2302
#define IDC_CHORD_RASTER                2303
#define IDC_CHORD_RASTER_COMBO          2304
#define IDC_ZOOM_SLIDER                 2305
#define IDC_ZOOM_TEXT                   2306
#define IDC_MINUS_TEXT                  2307
#define IDC_PLUS_TEXT                   2308
#define IDC_DELETE_COUNT_IN             2309
#define IDC_INSERT_COUNT_IN             2310
#define IDC_VEL_TEXT                    2313
#define IDC_MAINVOLUME_TO_EXPRESSION_TEXT 2315
#define IDC_MAINVOLUME_TO_EXPRESSION_CHECK 2316
#define IDC_EXPRESSION_TO_MAINVOLUME    2317
#define IDC_EXPRESSION_TO_MAINVOLUME_CHECK 2318
#define IDC_KBD_VOICE_EVENTS            2319
#define IDC_STYLE_SYSEX                 2320
#define IDC_NORMALIZE_CHORDS            2321
#define IDC_EDT_AVERAGE1                2322
#define IDC_EDT_AVERAGE2                2323
#define IDC_EDT_AVERAGE3                2324
#define IDC_EDT_AVERAGE4                2325
#define IDC_EDT_AVERAGE5                2326
#define IDC_EDT_AVERAGE6                2327
#define IDC_EDT_AVERAGE7                2328
#define IDC_EDT_AVERAGE8                2329
#define IDC_EDT_AVERAGE9                2330
#define IDC_EDT_AVERAGE10               2331
#define IDC_EDT_AVERAGE11               2332
#define IDC_EDT_AVERAGE12               2333
#define IDC_EDT_AVERAGE13               2334
#define IDC_EDT_AVERAGE14               2335
#define IDC_EDT_AVERAGE15               2336
#define IDC_EDT_AVERAGE16               2337
#define IDC_TXT_AVERAGE                 2338
#define IDC_BUTTON2                     2339
#define IDC_PREFERENCES                 2339
#define IDC_SPECIAL_PREFERENCES         2339
#define IDC_SCORE_NOTES_OPT             2339
#define IDC_OFF                         2339
#define IDC_CHANGE_DRUMS_BATCH          2339
#define IDC_FINISH                      2339
#define IDC_SCORE_LAYOUT                2339
#define IDC_START_RECORD                2339
#define IDC_VH_KANAL                    2340
#define IDC_VH_CHAN_TEXT                2342
#define IDC_VH_ACT_CHECK                2343
#define IDC_VH_DEACT_CHECK              2344
#define IDC_IDC_END_LYRIC_TEXT          2345
#define IDC_LINEFEED_LYRIC_CHECK        2347
#define IDC_NO_EFF_BLOCKS               2354
#define IDC_NO_EFF_BLOCKS_TXT           2355
#define IDC_VH_EFF_BLOCK_TXT            2356
#define IDC_VH_EFF_BLOCK                2357
#define IDC_CHECK_DCHAN                 2362
#define IDC_CHECK_DCHAN_TXT             2363
#define IDC_DELETE_DOUBLE_NOTES         2364
#define IDC_DELETE_DOUBLE_NOTES_TXT     2365
#define IDC_MP_CONVERT                  2366
#define IDC_MP_CONVERT_TXT              2367
#define IDC_DRUM_SETUP_CONVERT          2368
#define IDC_DRUM_SETUP_CONVERT_TXT      2369
#define IDC_FILL_SEQU_TRACK             2370
#define IDC_FILL_SEQU_TRACK_TXT         2371
#define IDC_ALLOW_ALIEN_SYSEX           2372
#define IDC_ALLOW_ALIEN_SYSEX_TXT       2373
#define IDC_ALLOW_ALIEN_VOICES          2374
#define IDC_ALLOW_ALIEN_VOICES_TXT      2376
#define IDC_SOURCE_CLOSE                2377
#define IDC_DELETE_NOT_DOUBLE_DRUM_NOTES 2379
#define IDC_DELET_NOT_DOUBLE_DRUM_NOTES_TXT 2380
#define IDC_VH_ACT_DEACT_FRAME          2381
#define IDC_CHECK_ACT_DEAKT             2382
#define IDC_LENGTHEN_NOTE               2383
#define IDC_CHECK_SELECT_LENGTHEN       2384
#define IDC_MAX_LENGTHEN_TXT            2385
#define IDC_NO_QUARTERS                 2386
#define IDC_QUARTER_NOTES_TXT           2387
#define IDC_CHECK_POSITION              2388
#define IDC_MEASURE_TXT                 2389
#define IDC_BEAT_TXT                    2390
#define IDC_BEAT                        2391
#define IDC_TICK_TXT                    2392
#define IDC_TICK                        2393
#define IDC_CHECK_READ_NOTE_AREA        2394
#define IDC_MBT_CHECK                   2396
#define IDC_WITH_MBT                    2397
#define IDC_SCORE_CHAN_LIST             2398
#define IDC_SCORE_CHAN_TXT              2399
#define IDC_MAX_TXT                     2400
#define IDC_NO_LYRICS_CUEPOINT          2401
#define IDC_QUANTIZE                    2402
#define IDC_SELECT_CHAN_TXT             2404
#define IDC_HALF_TXT                    2405
#define IDC_HALF_TRIOLE_TXT             2406
#define IDC_QUARTER_TXT                 2407
#define IDC_QUARTER_TRIOLE_TXT          2408
#define IDC_EIGHTTEENTH_TXT             2409
#define IDC_EIGHTTEENTH_TRIOLE_TXT      2410
#define IDC_16TH_TXT                    2411
#define IDC_32TH_TXT                    2412
#define IDC_64TH_TXT                    2413
#define IDC_RASTER_TXT                  2415
#define IDC_CHECK_WHOLE                 2416
#define IDC_CHECK_HALF                  2417
#define IDC_CHECK_HALF_TRIOLE           2418
#define IDC_CHECK_QUARTER               2419
#define IDC_CHECK_QUARTER_TRIOLE        2420
#define IDC_CHECK_EIGHTTEENTH           2421
#define IDC_CHECK_EIGHTTEENTH_TRIOLE    2422
#define IDC_CHECK_16TH                  2423
#define IDC_CHECK_32th                  2424
#define IDC_CHECK_64TH                  2425
#define IDC_SELECT_RASTER_TXT           2426
#define IDC_CHECK_NOTE_LENGTH           2427
#define IDC_CHECK_START_TIME            2428
#define IDC_CHECK_16TH_TRIOLE           2429
#define IDC_16TH_TRIOLE_TXT             2430
#define IDC_DELETE_SHORT_NOTES          2431
#define IDC_CHECK1                      2432
#define IDC_CHECK2                      2433
#define IDC_CHECK3                      2434
#define IDC_CHECK4                      2435
#define IDC_CHECK5                      2436
#define IDC_CHECK6                      2437
#define IDC_CHECK7                      2438
#define IDC_CHECK8                      2439
#define IDC_CHECK9                      2440
#define IDC_CHECK10                     2441
#define IDC_CHECK11                     2442
#define IDC_CHECK12                     2443
#define IDC_CHECK13                     2444
#define IDC_CHECK14                     2445
#define IDC_CHECK15                     2446
#define IDC_CHECK16                     2447
#define IDC_INCL                        2448
#define IDC_UPTO_TICK                   2449
#define IDC_TICKS                       2450
#define IDC_MIN_LENGTH                  2451
#define IDC_MIN_LEN1                    2452
#define IDC_MIN_LEN2                    2453
#define IDC_MIN_LEN3                    2454
#define IDC_MIN_LEN4                    2455
#define IDC_MIN_LEN5                    2456
#define IDC_MIN_LEN6                    2457
#define IDC_MIN_LEN7                    2458
#define IDC_MIN_LEN8                    2459
#define IDC_MIN_LEN9                    2460
#define IDC_MIN_LEN10                   2461
#define IDC_MIN_LEN11                   2462
#define IDC_MIN_LEN12                   2463
#define IDC_MIN_LEN13                   2464
#define IDC_MIN_LEN14                   2465
#define IDC_MIN_LEN15                   2466
#define IDC_MIN_LEN16                   2467
#define IDC_DELETE_MIDI_EVENTS          2468
#define IDC_FRAME                       2469
#define IDC_MIDI_EVENT_COMBOBOX         2470
#define IDC_MIDI_EVENT                  2471
#define IDC_NO1                         2472
#define IDC_NO2                         2473
#define IDC_NO3                         2474
#define IDC_NO4                         2475
#define IDC_NO5                         2476
#define IDC_NO6                         2477
#define IDC_NO7                         2478
#define IDC_NO8                         2479
#define IDC_NO9                         2480
#define IDC_NO10                        2481
#define IDC_NO11                        2482
#define IDC_NO12                        2483
#define IDC_NO13                        2484
#define IDC_NO14                        2485
#define IDC_NO15                        2486
#define IDC_NO16                        2487
#define IDC_NO_ALL                      2488
#define IDC_NUMBER                      2489
#define IDC_NOTE_AREA                   2490
#define IDC_EDIT_NOTE_AREA              2491
#define IDC_BEFORE_NOTES                2492
#define IDC_EDIT_BEFORE_NOTES           2493
#define IDC_ALL                         2494
#define IDC_XG_EFFECTDEF                2496
#define IDC_XG_DEF_FILENAME             2497
#define IDC_IGNORE                      2499
#define IDC_KEYBOARDCOMBOBOX            2500
#define IDC_FILL_LYRIC_FRAME            2504
#define IDC_USER_FRAME                  2505
#define IDC_USER2_FILL_LYRICS           2506
#define IDC_USER3_FILL_LYRICS           2507
#define IDC_LYRICS_FRAME                2508
#define IDC_DRUMS                       2509
#define IDC_LYRICS_BITMAP_EVENTS        2510
#define IDC_GUIDE_TRACK_FLAG            2511
#define IDC_SCORE_START_BAR             2512
#define IDC_PHRASE_METAS                2513
#define IDC_CONVERT_GM                  2514
#define IDC_LENGTHEN                    2515
#define IDC_PERCENT_LIST                2516
#define IDC_TEMPO_CHECK                 2517
#define IDC_PROGRESSCTRL                2518
#define IDC_TIME_SIGNATURE              2519
#define IDC_NUM                         2520
#define IDC_DENUM                       2521
#define IDC_NUM_TXT                     2522
#define IDC_DENUM_TXT                   2523
#define IDC_ACT_TIME                    2524
#define IDC_BEFORE_FIRST_NOTES_FRAME    2525
#define IDC_NOTE_AREA_FRAME             2526
#define IDC_ABORT_NOTE_AREA             2528
#define IDC_EXPORT_NOTE_AREA            2529
#define IDC_IMPORT_NOTE_AREA            2530
#define IDC_SWITCH                      2531
#define IDC_DELETE_FILL_LYRICS          2532
#define IDC_FL1_TXT                     2533
#define IDC_FL2_TXT                     2534
#define IDC_FL3_TXT                     2535
#define IDC_FL2                         2536
#define IDC_FL3                         2537
#define IDC_KLICKSPUR                   2538
#define IDC_MEASURE_DRUM_FRAME          2539
#define IDC_BEAT_DRUM_FRAME             2540
#define IDC_MEASURE_DRUM_COMBO          2541
#define IDC_BEAT_DRUM_COMBO             2542
#define IDC_MEASURE_DRUM_MAINVOLUME_TXT 2543
#define IDC_MEASURE_DRUM_VELOCITY_TXT   2544
#define IDC_MEASURE_DRUM_VELOCITY       2545
#define IDC_BEAT_DRUM_VELOCITY          2546
#define IDC_BEAT_DRUM_VELOCTY_TXT       2547
#define IDC_SLIDER_MASTER_VOLUME        2548
#define IDC_VOLUME_DISPLAY              2549
#define IDC_MAX_NOTES_LIST              2550
#define IDC_Max_NOTE_LENGTH_Txt         2551
#define IDC_LINEFEED                    2554
#define IDC_NEWPAGE                     2555
#define IDC_GUIDE                       2556
#define IDC_DRUMS_FROM_INSFILE          2557
#define IDC_DRUMS_FROM_INSFILE_TXT      2558
#define IDC_SP_MARKER                   2559
#define IDC_VH_EVENTS_DELETE            2560
#define IDC_VH_EVENTS_DELETE_TEXT       2561
#define IDC_ONE_MEASURE_TEXT            2562
#define IDC_CHECK_ONE_MEASURE           2563
#define IDC_SCORE                       2564
#define IDC_SCORENOTESOPT               2565
#define IDC_LYRICCOMBOBOX               2566
#define IDC_LYRICSTXT                   2567
#define IDC_CHORDSCOMBO                 2568
#define IDC_CHORDSTXT                   2569
#define IDC_SIZECOMBOBOX                2570
#define IDC_NOTENAMESTXT                2571
#define IDC_NOTENAMESTYPE               2572
#define IDC_QUANTIZETXT                 2573
#define IDC_QUANTIZETRIOLETXT           2574
#define IDC_NOTECOLOURTXT               2575
#define IDC_NOTENAMESCOMBO              2576
#define IDC_NOTENAMESTYPECOMBO          2577
#define IDC_QUANTIZECOMBO               2578
#define IDC_QUANTIZETRIOLECOMBO         2579
#define IDC_NOTECOLOURCOMBO             2580
#define IDC_SELECT_VOCODER_CHAN         2581
#define IDC_DELETE_VOCODER_CHAN         2588
#define IDC_VOCODER_CHANNEL             2589
#define IDC_VH_CHAN_LIST                2591
#define IDC_SELECT                      2592
#define IDC_DESELECT                    2593
#define IDC_VOCODER_CHANNEL_TXT         2594
#define IDC_CHANNEL_LIST                2595
#define IDC_MSB_NUMBER                  2596
#define IDC_EDIT_LSB                    2597
#define IDC_LSB_NUMBER                  2598
#define IDC_EDIT_BANKNUMBER             2599
#define IDC_PLUS                        2600
#define IDC_IS                          2601
#define IDC_CHECK_WITHOUT_SYSEX_DRUMKIT_MODE 2602
#define IDC_SYSEX_DRUMKIT_TXT           2603
#define IDC_LYRIC_RECORDING_FRAME       2604
#define IDC_LYRIC_LINES                 2605
#define IDC_NEXT_LYRIC                  2606
#define IDC_SELECT_WORDS_SYLLABLES      2607
#define IDC_SELECT_LYRIC_LINES          2608

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2609
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
